-- Se utiliza para listar los contenedores en: 
-- Control de Parqueos y contenedores
IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXCONTENEDORES') DROP VIEW DAXCONTENEDORES
 GO 
CREATE VIEW [dbo].[DAXCONTENEDORES] AS
SELECT A.SHIPCPYCONTAINERID,
       A.SHIPCPYCONTAINERSTATE,
       A.SHIPCPYCUSTOMMARKID,
       A.SHIPCPYEXPECTEDDATE,
       A.SHIPCPYREALDATETIME,
       A.DATAAREAID,
       B.NAME,
       B.PARKINGPOSITIONID,
       B.PARKINGSPACETRANSTYPE,
       C.PARKINGSECTORID,
       D.PARKINGSPACEID,
       D.NAME AS SITIO,
       E.INTRASTATTRANSPORT,
	   (SELECT TOP 1 T1.SHIPCPYCUSTOMMARKID1
    FROM SHIPCPYCONTAINERTRANS T1
    WHERE T1.SHIPCPYCONTAINERTABLERECID = A.RECID
    ORDER BY T1.CREATEDDATETIME DESC, T1.RECID DESC) CUSTOMMARKID
FROM dbo.SHIPCPYCONTAINERTABLE AS A
INNER JOIN dbo.PARKINGPOSITIONTABLE AS B ON A.RECID = B.SHIPCPYCONTAINERTABLERECID
INNER JOIN dbo.PARKINGSECTORTABLE AS C ON B.PARKINGSECTORTABLERECID = C.RECID
INNER JOIN dbo.PARKINGSPACETABLE AS D ON D.RECID = C.PARKINGSPACETABLERECID
INNER JOIN dbo.SHIPPINGCPYVENDTABLE AS E ON E.RECID = A.SHIPPINGCPYVENDTABLERECID
