-- Se utiliza para listar los contenedores en: 
-- Control de Parqueos y contenedores
ALTER VIEW [dbo].[DAXCONTENEDORES] AS
SELECT A.SHIPCPYCONTAINERID,
       A.SHIPCPYCONTAINERSTATE,
       A.SHIPCPYCUSTOMMARKID,
       A.SHIPCPYEXPECTEDDATE,
       A.SHIPCPYREALDATETIME,
       A.DATAAREAID,
       B.NAME,
       B.PARKINGPOSITIONID,
       B.PARKINGSPACETRANSTYPE,
       C.PARKINGSECTORID,
       D.PARKINGSPACEID,
       D.NAME AS SITIO,
       E.INTRASTATTRANSPORT
FROM dbo.SHIPCPYCONTAINERTABLE AS A
INNER JOIN dbo.PARKINGPOSITIONTABLE AS B ON A.RECID = B.SHIPCPYCONTAINERTABLERECID
INNER JOIN dbo.PARKINGSECTORTABLE AS C ON B.PARKINGSECTORTABLERECID = C.RECID
INNER JOIN dbo.PARKINGSPACETABLE AS D ON D.RECID = C.PARKINGSPACETABLERECID
INNER JOIN dbo.SHIPPINGCPYVENDTABLE AS E ON E.RECID = A.SHIPPINGCPYVENDTABLERECID