IF OBJECT_ID('dbo.DAXINVENTTRANSFERTABLELINE', 'V') IS NOT NULL
DROP VIEW dbo.DAXINVENTTRANSFERTABLELINE GO
CREATE VIEW [dbo].[DAXINVENTTRANSFERTABLELINE] AS
SELECT DISTINCT E.TRANSFERID,
                E.INVENTLOCATIONIDFROM,
                E.INVENTLOCATIONIDTO,
                E.FROMADDRESSNAME,
                E.TOADDRESSNAME,
                E.TRANSFERSTATUS,
                E.DATAAREAID,
                E.SHIPDATE,
                E.DateAsInt,
                D.ITEMID,
                E.RECVERSION,
                D.QTYTRANSFER,
                D.PDSCWQTYTRANSFER,
                F.INVENTSITEID AS SITE_FROM,
                T.INVENTSITEID AS SITE_TO,
                D.LINENUM,
                O.INVENTBATCHID,
                ID_TO.WMSLOCATIONID AS WMSLOCATIONID_TO,
                ID_FROM.WMSLOCATIONID AS WMSLOCATIONID_FROM,

  (SELECT top 1 DIOT.CREATEDUSERID
   FROM dbo.DAXINVENTORDERTRANSFER DIOT
   WHERE DIOT.TRANSFERID = E.TRANSFERID
     AND DIOT.ITEMID = D.ITEMID
     AND DIOT.LINENUMBER = D.LINENUM ) AS CREATEDUSERID
FROM dbo.INVENTTRANSFERTABLE AS E
INNER JOIN dbo.INVENTTRANSFERLINE AS D ON E.TRANSFERID = D.TRANSFERID
AND E.DATAAREAID = D.DATAAREAID
INNER JOIN dbo.INVENTLOCATION AS F ON E.INVENTLOCATIONIDFROM = F.INVENTLOCATIONID
INNER JOIN dbo.INVENTLOCATION AS T ON E.INVENTLOCATIONIDTO = T.INVENTLOCATIONID
INNER JOIN dbo.INVENTDIM AS O ON D.INVENTDIMID = O.INVENTDIMID
INNER JOIN dbo.INVENTTRANSORIGIN AS ITO_TO ON D.INVENTTRANSIDRECEIVE = ITO_TO.INVENTTRANSID
INNER JOIN dbo.INVENTTRANS AS IT_TO ON ITO_TO.RECID = IT_TO.INVENTTRANSORIGIN
INNER JOIN dbo.INVENTDIM AS ID_TO ON IT_TO.INVENTDIMID = ID_TO.INVENTDIMID
INNER JOIN dbo.INVENTTRANSORIGIN AS ITO_FROM ON D.INVENTTRANSID = ITO_FROM.INVENTTRANSID
INNER JOIN dbo.INVENTTRANS AS IT_FROM ON ITO_FROM.RECID = IT_FROM.INVENTTRANSORIGIN
INNER JOIN dbo.INVENTDIM AS ID_FROM ON IT_FROM.INVENTDIMID = ID_FROM.INVENTDIMID