IF OBJECT_ID('dbo.DAXITEMSNOTBLOCK', 'V') IS NOT NULL
DROP VIEW dbo.DAXITEMSNOTBLOCK GO
CREATE VIEW [dbo].[DAXITEMSNOTBLOCK] AS
SELECT DISTINCT T3.ITEMID,
                T2.NAME,
                T1.DATAAREAID,
                T1.STOPPED
FROM dbo.INVENTITEMINVENTSETUP AS T1
INNER JOIN dbo.INVENTTABLE AS T3 ON T1.ITEMID = T3.ITEMID
INNER JOIN dbo.ECORESPRODUCTTRANSLATION AS T2 ON T2.PRODUCT = T3.PRODUCT
INNER JOIN dbo.INVENTDIM AS T4 ON T1.INVENTDIMID = T4.INVENTDIMID
WHERE (T1.STOPPED = 0)
  AND (T1.INVENTDIMID = 'AllBlank')
  AND (T2.LANGUAGEID = N'es-mx')