IF OBJECT_ID('dbo.DAXSALESORDERVIEW', 'V') IS NOT NULL
DROP VIEW dbo.DAXSALESORDERVIEW GO
CREATE VIEW [dbo].[DAXSALESORDERVIEW] AS
SELECT ST.SALESNAME AS SALESNAME_OLD,
       DPT.NAME AS SALESNAME,
       SL.SALESID,
       SL.LINENUM,
       SL.ITEMID,
       SL.DATAAREAID,
       SL.SALESQTY,
       SL.SALESPRICE,
       SL.QTYORDERED,
       SL.PDSCWQTY AS PDSCWQTYSALE,
       SL.SALESUNIT,
       IT.QTY,
       IT.PDSCWQTY AS PDSCWQTYRES,
       AL.INVENTLOCATIONID,
       AL.INVENTBATCHID,
       AL.WMSLOCATIONID,
       SL.NAME AS NAME_DEFAULT,
       SL.LINEAMOUNT,
       ERPT.NAME
FROM dbo.SALESLINE AS SL
INNER JOIN dbo.INVENTTRANSORIGIN AS ITO ON ITO.PARTITION = SL.PARTITION
AND ITO.DATAAREAID = SL.DATAAREAID
AND ITO.INVENTTRANSID = SL.INVENTTRANSID
INNER JOIN dbo.INVENTTRANS AS IT ON IT.PARTITION = ITO.PARTITION
AND IT.DATAAREAID = ITO.DATAAREAID
AND IT.INVENTTRANSORIGIN = ITO.RECID
INNER JOIN dbo.INVENTDIM AS AL ON IT.INVENTDIMID = AL.INVENTDIMID
AND IT.PARTITION = AL.PARTITION
INNER JOIN dbo.INVENTTABLE AS ITL ON SL.ITEMID = ITL.ITEMID
AND SL.DATAAREAID = ITL.DATAAREAID
INNER JOIN dbo.ECORESPRODUCTTRANSLATION AS ERPT ON ITL.PRODUCT = ERPT.PRODUCT
AND ITL.PARTITION = ERPT.PARTITION
INNER JOIN dbo.SALESTABLE AS ST ON SL.SALESID = ST.SALESID
INNER JOIN dbo.CUSTTABLE AS CT ON ST.CUSTACCOUNT = CT.ACCOUNTNUM
AND ST.DATAAREAID = CT.DATAAREAID
INNER JOIN dbo.DIRPARTYTABLE AS DPT ON CT.PARTY = DPT.RECID
WHERE (SL.PARTITION = 5637144576)
  AND (IT.STATUSISSUE = 4)
  AND ERPT.LANGUAGEID = N'es-mx'