IF OBJECT_ID('dbo.FISCALYEAR', 'V') IS NOT NULL
DROP VIEW dbo.FISCALYEAR GO
CREATE VIEW [dbo].[FISCALYEAR] AS
SELECT DISTINCT T1.RECID,
                T1.NAME,
                T1.STARTDATE,
                T1.ENDDATE,
                T1.STARTD,
                T1.ENDD,
                T2.STATUS,
                T3.NAME AS DATAAREAID
FROM dbo.FISCALCALENDARPERIOD AS T1
INNER JOIN dbo.LEDGERFISCALCALENDARPERIOD AS T2 ON T1.RECID = T2.FISCALCALENDARPERIOD
INNER JOIN dbo.LEDGER AS T3 ON T2.LEDGER = T3.RECID
WHERE (T1.NAME <> 'Período 0')