-- Se utiliza para mostrar los articulos en:
-- Diarios de Transferencia
CREATE VIEW [dbo].[DAXINVENT_TRANSFERJOURNAL] AS
SELECT T1.ITEMID,
       T1.NAMEALIAS,
       T1.DATAAREAID,
       T1.PARTITION,
       T1.RECID,
       T2.DATAAREAID AS DATAAREAID#2,
       T2.PARTITION AS PARTITION#2,
       T2.AVAILPHYSICAL,
       T2.RESERVPHYSICAL,
       T2.PHYSICALINVENT,
       T2.AVAILORDERED,
       T2.PDSCWAVAILORDERED,
       T2.PDSCWPHYSICALINVENT,
       T2.PDSCWAVAILPHYSICAL,
       T3.DATAAREAID AS DATAAREAID#3,
       T3.PARTITION AS PARTITION#3,
       T3.INVENTSITEID,
       T3.INVENTLOCATIONID,
       T3.WMSLOCATIONID,
       T3.INVENTBATCHID,
       T3.INVENTSERIALID,
       T3.CONFIGID,
       T3.INVENTCOLORID,
       T3.INVENTSIZEID,
       T3.INVENTSTYLEID,
       T3.INVENTSTATUSID,
       T3.LICENSEPLATEID,
       T4.PARTITION AS PARTITION#4,
       T4.NAME
FROM dbo.INVENTTABLE AS T1
INNER JOIN dbo.INVENTSUM AS T2 ON T1.ITEMID = T2.ITEMID
AND T1.DATAAREAID = T2.DATAAREAID
AND T1.PARTITION = T2.PARTITION
INNER JOIN dbo.INVENTDIM AS T3 ON T2.INVENTDIMID = T3.INVENTDIMID
AND T2.DATAAREAID = T3.DATAAREAID
AND T2.PARTITION = T3.PARTITION
INNER JOIN dbo.ECORESPRODUCTTRANSLATION AS T4 ON T1.PRODUCT = T4.PRODUCT
AND T1.PARTITION = T4.PARTITION
INNER JOIN dbo.INVENTITEMINVENTSETUP AS T5 ON T1.ITEMID = T5.ITEMID
AND T1.DATAAREAID = T5.DATAAREAID
AND T1.PARTITION = T5.PARTITION
WHERE (T4.LANGUAGEID = N'es-mx')
AND (T5.INVENTDIMID = 'AllBlank')
AND (T5.STOPPED = 0)