-- Se utiliza para mostrar los articulos en:
-- Control de parqueos y contenedores -> Traslado preparado externo
CREATE VIEW [dbo].[DAXINVENTTABLESHIPCONTAINERBLOCK] AS
SELECT DISTINCT 
	T1.ITEMID, 
	T1.NAMEALIAS, 
	T6.NAME, 
	T2.ITEMGROUPID
FROM INVENTTABLE T1
INNER JOIN INVENTITEMGROUPITEM T2 ON T1.ITEMID = T2.ITEMID AND T1.DATAAREAID = T2.ITEMDATAAREAID 
INNER JOIN INVENTITEMGROUP T3 ON T2.ITEMGROUPID = T3.ITEMGROUPID AND T2.ITEMGROUPDATAAREAID = T3.DATAAREAID
INNER JOIN INVENTITEMPURCHSETUP T4 ON T1.ITEMID = T4.ITEMID AND T1.DATAAREAID = T4.DATAAREAID 
INNER JOIN ECORESPRODUCT T5 ON T1.PRODUCT = T5.RECID 
INNER JOIN ECORESPRODUCTTRANSLATION T6 ON T5.RECID = T6.PRODUCT
WHERE 
T6.LANGUAGEID = 'es-mx'
AND T3.SHIPCPYCONTAINERUSE = 1
AND T4.STOPPED = 0
AND T4.INVENTDIMID = 'AllBlank'
AND T4.INVENTDIMIDDEFAULT = 'AllBlank'
AND T1.DATAAREAID = 'lx'