IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXINVENTJOURNALUNIT') DROP VIEW DAXINVENTJOURNALUNIT
GO
CREATE VIEW [dbo].[DAXINVENTJOURNALUNIT] AS
SELECT DISTINCT T1.SYMBOL, T3.ITEMID, T3.DATAAREAID
FROM UNITOFMEASURE T1
INNER JOIN UNITOFMEASURECONVERSION T2 ON T1.RECID = T2.FROMUNITOFMEASURE
INNER JOIN INVENTTABLE T3 ON T2.PRODUCT = T3.PRODUCT
GO