IF OBJECT_ID('dbo.DAXPARKINGSUMMARYBYSITE', 'V') IS NOT NULL
DROP VIEW dbo.DAXPARKINGSUMMARYBYSITE GO
CREATE VIEW [dbo].[DAXPARKINGSUMMARYBYSITE] AS
SELECT PARKINGSPACEID,
       PARKINGSPACENAME,

  (SELECT COUNT(*) AS Expr1
   FROM
     (SELECT PARKINGSECTORID
      FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
      WHERE (T1.PARKINGSPACEID = PARKINGSPACEID)
      GROUP BY PARKINGSECTORID) AS t1) AS SECTORS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = PARKINGSPACEID)
     AND (PARKINGSPACETRANSTYPE = 0)) AS AVAILPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = PARKINGSPACEID)
     AND (SHIPPINGCPYTYPE = 0)) AS COMMERCIALCONTAINERS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = PARKINGSPACEID)
     AND (SHIPPINGCPYTYPE = 1)) AS OWNCONTAINERS
FROM dbo.DAXPARKINGPOSITIONTABLE AS T1
GROUP BY PARKINGSPACEID,
         PARKINGSPACENAME