IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXPARKINGSUMMARYBYSITE') DROP VIEW DAXPARKINGSUMMARYBYSITE
GO
CREATE VIEW [dbo].[DAXPARKINGSUMMARYBYSITE] AS
SELECT PARKINGSPACEID,
       PARKINGSPACENAME,

  (SELECT COUNT(*) AS Expr1
   FROM
     (SELECT PARKINGSECTORID
      FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
      WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
	    AND dppt.PARKINGINACTIVE = 0
      GROUP BY dppt.PARKINGSECTORID) AS t1) AS SECTORS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.PARKINGSPACETRANSTYPE = 0)) AS AVAILPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.PARKINGSPACETRANSTYPE = 2)) AS RESERVEDPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.PARKINGSPACETRANSTYPE in (4,3,9,10,7))) AS TAKENPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND (dppt.PARKINGINACTIVE = 1)) AS INACTIVEPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0) AS TOTALPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.SHIPPINGCPYTYPE = 0)) AS COMMERCIALCONTAINERS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.SHIPPINGCPYTYPE = 1)) AS OWNCONTAINERS,

  (SELECT COUNT(*) AS Expr1
   FROM
     (SELECT dppt.SHIPCPYCONTAINERID
      FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
      WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID) AND (dppt.SHIPCPYCONTAINERID IS NOT NULL)
	  AND dppt.PARKINGINACTIVE = 0
      GROUP BY SHIPCPYCONTAINERID) AS t1) AS TOTALCONTAINERS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.SHIPPINGCPYTYPE = 0)
	 AND (dppt.PARKINGSPACETRANSTYPE in (4,3,9,10,7))) AS TAKENCOMMERCIALCONTAINERS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND dppt.PARKINGINACTIVE = 0
     AND (dppt.SHIPPINGCPYTYPE = 1)
	 AND (dppt.PARKINGSPACETRANSTYPE in (4,3,9,10,7))) AS TAKENOWNCONTAINERS

FROM dbo.DAXPARKINGPOSITIONTABLE AS T1
WHERE T1.PARKINGINACTIVE = 0
GROUP BY PARKINGSPACEID,
         PARKINGSPACENAME
GO