IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXPALLETFILLSTATUSBYSITE') DROP VIEW [DAXPALLETFILLSTATUSBYSITE]
GO
CREATE VIEW [dbo].[DAXPALLETFILLSTATUSBYSITE] AS
SELECT TMP1.PARKINGSPACEID,TMP1.RANGEDESCRIPTION,ISNULL(TMP2.TOTALCONTAINERS,0) TOTALCONTAINERS 
FROM (
	SELECT T1.RANGEDESCRIPTION, T2.PARKINGSPACEID
	FROM (
		SELECT 'Pallets ocupadas en su totalidad' RANGEDESCRIPTION UNION
		SELECT 'Pallets ocupadas parcialmente' RANGEDESCRIPTION UNION
		SELECT 'Pallets ocupadas menos de la mitad' RANGEDESCRIPTION UNION
		SELECT 'Pallets libres' RANGEDESCRIPTION
	) T1,
	(
		SELECT DISTINCT PARKINGSPACEID 
		FROM DAXWMSLOCATIONBYCONTAINER
		WHERE PARKINGSPACEID IS NOT NULL
	) T2
) TMP1
LEFT JOIN
(
	SELECT tbl1.PARKINGSPACEID, tbl1.RANGEDESCRIPTION, COUNT(*) TOTALCONTAINERS 
	FROM (
		SELECT
		t3.PARKINGSPACEID, 
		(t1.INVENTQTYAVAILPHYSICAL / (t2.MAXWEIGHT / t2.QTYLOCATIONS))*100 AS PERCENTFILL,
		CASE
			WHEN (t1.INVENTQTYAVAILPHYSICAL / (t2.MAXWEIGHT / t2.QTYLOCATIONS))*100 > 99.00 THEN 'Pallets ocupadas en su totalidad'
			WHEN (t1.INVENTQTYAVAILPHYSICAL / (t2.MAXWEIGHT / t2.QTYLOCATIONS))*100 BETWEEN 50.00 AND 98.99 THEN 'Pallets ocupadas parcialmente'
			WHEN (t1.INVENTQTYAVAILPHYSICAL / (t2.MAXWEIGHT / t2.QTYLOCATIONS))*100 BETWEEN 0.01 AND 49.99 THEN 'Pallets ocupadas menos de la mitad'
			WHEN (t1.INVENTQTYAVAILPHYSICAL / (t2.MAXWEIGHT / t2.QTYLOCATIONS))*100 = 0.00 THEN 'Pallets libres'
		END RANGEDESCRIPTION
		FROM DAXWMSLOCATIONAVAILPHYSICAL t1
		INNER JOIN SHIPCPYCONTAINERTABLE t2 ON t1.inventlocationid = t2.SHIPCPYCONTAINERID 
		INNER JOIN DAXWMSLOCATIONBYCONTAINER t3 ON t1.INVENTLOCATIONID = t3.SHIPCPYCONTAINERID AND t1.WMSLOCATIONID = t3.WMSLOCATIONID
		WHERE t2.SHIPCPYCONTAINERSTATE <> 2
	) AS tbl1
	GROUP BY tbl1.PARKINGSPACEID, tbl1.RANGEDESCRIPTION
) TMP2 ON TMP1.PARKINGSPACEID = TMP2.PARKINGSPACEID
	AND TMP1.RANGEDESCRIPTION = TMP2.RANGEDESCRIPTION
GO