IF OBJECT_ID('dbo.DAXPARKINGFILLCONTAINER', 'V') IS NOT NULL
DROP VIEW dbo.DAXPARKINGFILLCONTAINER GO
CREATE VIEW [dbo].[DAXPARKINGFILLCONTAINER] AS
SELECT T1.PARKINGSPACEID,
       T1.PARKINGSPACENAME,
       T1.PARKINGSECTORID,
       T1.PARKINGSECTORNAME,
       T1.SHIPCPYCONTAINERID,
       T1.SHIPCPYEXPECTEDEXITDATE,
       T1.PARKINGSPACETRANSTYPE,
       T1.PARKINGSPACETRANSTYPE_DESC,
       T1.MAXWEIGHT,
       CASE
           WHEN T2.INVENTQTYAVAILPHYSICAL IS NOT NULL THEN T2.INVENTQTYAVAILPHYSICAL
           ELSE 0
       END AS INVENTQTYAVAILPHYSICAL,
       CASE
           WHEN T2.MAXWEIGHT != 0 THEN ROUND((T2.INVENTQTYAVAILPHYSICAL / T2.MAXWEIGHT) * 100, 2)
           ELSE 0
       END AS PERCENTFILLCONTAINER
FROM dbo.DAXPARKINGPOSITIONTABLE AS T1
LEFT OUTER JOIN
  (SELECT SHIPCPYCONTAINERID,
          SHIPPINGCPYTYPE,
          SUM(INVENTQTYPHYSICALONHAND) AS INVENTQTYPHYSICALONHAND,
          SUM(INVENTQTYAVAILPHYSICAL) AS INVENTQTYAVAILPHYSICAL,
          SUM(INVENTQTYRESERVPHYSICAL) AS INVENTQTYRESERVPHYSICAL,
          SUM(PDSCWAVAILPHYSICAL) AS PDSCWAVAILPHYSICAL,
          SUM(PDSCWPHYSICALINVENT) AS PDSCWPHYSICALINVENT,
          SUM(POSTEDVALUE) AS POSTEDVALUE,
          SUM(COSTPRICE) AS COSTPRICE,
          SUM(PDSCWCOSTPRICE) AS PDSCWCOSTPRICE,
          MIN(MAXWEIGHT) AS MAXWEIGHT
   FROM dbo.DAXINVENTONHANDCONTAINER
   GROUP BY SHIPCPYCONTAINERID,
            SHIPPINGCPYTYPE) AS T2 ON T1.SHIPCPYCONTAINERID = T2.SHIPCPYCONTAINERID
WHERE (T1.SHIPCPYCONTAINERID IS NOT NULL)