IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXPARKINGSUMMARYBYSECTOR') DROP VIEW DAXPARKINGSUMMARYBYSECTOR
GO
CREATE VIEW [dbo].[DAXPARKINGSUMMARYBYSECTOR] AS
SELECT PARKINGSPACEID,
       PARKINGSPACENAME,
       PARKINGSECTORID,
       PARKINGSECTORNAME,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = dppt.PARKINGSECTORID)
     AND (dppt.PARKINGINACTIVE = 0)
     AND (dppt.PARKINGSPACETRANSTYPE = 0)) AS AVAILPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = dppt.PARKINGSECTORID)
     AND (dppt.PARKINGINACTIVE = 0)
     AND (dppt.PARKINGSPACETRANSTYPE = 2)) AS RESERVEDPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = dppt.PARKINGSECTORID)
     AND (dppt.PARKINGINACTIVE = 0)
     AND (dppt.PARKINGSPACETRANSTYPE in (4,3,9,10,7))) AS TAKENPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = dppt.PARKINGSECTORID)
     AND (dppt.PARKINGINACTIVE = 1)) AS INACTIVEPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = dppt.PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = dppt.PARKINGSECTORID)) AS TOTALPOSITION,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = PARKINGSECTORID)
     AND (dppt.PARKINGINACTIVE = 0)
     AND (dppt.SHIPPINGCPYTYPE = 0)
	 AND (dppt.PARKINGSPACETRANSTYPE in (4,3,9,10,7))) AS COMMERCIALCONTAINERS,

  (SELECT COUNT(*) AS Expr1
   FROM dbo.DAXPARKINGPOSITIONTABLE AS dppt
   WHERE (T1.PARKINGSPACEID = PARKINGSPACEID)
     AND (T1.PARKINGSECTORID = PARKINGSECTORID)
     AND (dppt.PARKINGINACTIVE = 0)
     AND (dppt.SHIPPINGCPYTYPE = 1)
	 AND (dppt.PARKINGSPACETRANSTYPE in (4,3,9,10,7))) AS OWNCONTAINERS

FROM dbo.DAXPARKINGPOSITIONTABLE AS T1
GROUP BY PARKINGSPACEID,
         PARKINGSPACENAME,
         PARKINGSECTORID,
         PARKINGSECTORNAME
GO