IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXPARKINGFILLWMSLOCATION') DROP VIEW [DAXPARKINGFILLWMSLOCATION]
GO
CREATE VIEW [dbo].[DAXPARKINGFILLWMSLOCATION] AS
SELECT t1.SHIPCPYCONTAINERID,
       t1.WMSLOCATIONID,
       t1.INVENTQTYAVAILPHYSICAL,
       ROUND(iif(t1.QtyConvert01ByUnitAvg > 0, (t1.INVENTQTYAVAILPHYSICAL/t1.QtyConvert01ByUnitAvg)*100, 0),2) AS PERCENTFILLPALLET,
       t1.ITEMSINPALLET
FROM
  (SELECT tmp.shipcpycontainerrecid,
          tmp.SHIPCPYCONTAINERID,
          tmp.wmslocationid,
          SUM(tmp.INVENTQTYAVAILPHYSICAL) AS INVENTQTYAVAILPHYSICAL,
          isnull(AVG(tmp.QtyConvert01ByUnit), 0) AS QtyConvert01ByUnitAvg,
          COUNT(*) AS ITEMSINPALLET
   FROM daxinventonhandcontainer tmp
   GROUP BY tmp.shipcpycontainerrecid,
            tmp.wmslocationid,
            tmp.SHIPCPYCONTAINERID) AS t1
GO