IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXSHIPCPYCONTAINERPILOTCONFIG') DROP VIEW DAXALLITEMIDS
GO
CREATE VIEW [dbo].[DAXSHIPCPYCONTAINERPILOTCONFIG] AS 
SELECT T2.SHIPCPYCONTAINERID,
       T1.SHIPCPYCONTAINERPILOTTYPE,
       CASE T1.SHIPCPYCONTAINERPILOTTYPE
           WHEN 1 THEN 'Entrada'
           WHEN 2 THEN 'Salida'
       END SHIPCPYCONTAINERPILOTTYPE_DESC,
       T3.SHIPPINGCPYVENDTABLEPILOTID,
       T3.NAME,
       T4.DOCUMENTTYPEIDENTIFICATIONID,
       T4.SHIPCPYPILOTDOCUMENTNUM,
       T5.SHIPPINGCPYVENDTABLEVEHICLESID
FROM SHIPCPYCONTAINERPILOT T1
INNER JOIN SHIPCPYCONTAINERTABLE T2 ON T1.SHIPCPYCONTAINERTABLERECID = T2.RECID
INNER JOIN SHIPPINGCPYVENDTABLEPILOT T3 ON T1.SHIPPINGCPYVENDTABLEPILOTRECID = T3.RECID
INNER JOIN SHIPPINGCPYVENDTABLEPILOTDOCUMENT T4 ON T1.SHIPPINGCPYVENDTABLEPILOTDOCUMENTRECID = T4.RECID
INNER JOIN SHIPPINGCPYVENDTABLEVEHICLES T5 ON T1.SHIPPINGCPYVENDTABLEVEHICLESRECID = T5.RECID
GO