IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXSTATUSBATCHIDBYSITE') DROP VIEW DAXSTATUSBATCHIDBYSITE
GO
CREATE VIEW [dbo].[DAXSTATUSBATCHIDBYSITE] AS
SELECT TMP1.PARKINGSPACEID,TMP1.STATUSBATCHID,ISNULL(TMP2.STATUSCOUNT,0) STATUSCOUNT FROM
(SELECT T1.STATUSBATCHID, T2.PARKINGSPACEID
FROM (
	SELECT 'Lotes Vencidos' STATUSBATCHID UNION
	SELECT 'Lotes Por Vencer Hoy' STATUSBATCHID UNION
	SELECT 'Lotes No Vencidos' STATUSBATCHID
	) T1,
	(
	SELECT DISTINCT PARKINGSPACEID 
	FROM DAXINVENTONHANDCONTAINER
	WHERE PARKINGSPACEID IS NOT NULL
	) T2
) TMP1
LEFT JOIN
(SELECT T2.PARKINGSPACEID, T2.STATUSBATCHID, COUNT(*) STATUSCOUNT
FROM
(SELECT DISTINCT 
	T1.PARKINGSPACEID,
	T1.INVENTBATCHID,
	T1.EXPDATE, 
	CASE
		WHEN DATEDIFF(DAY, GETDATE(), T1.EXPDATE) < 0 THEN 'Lotes Vencidos'
		WHEN DATEDIFF(DAY, GETDATE(), T1.EXPDATE) = 0 THEN 'Lotes Por Vencer Hoy'
		WHEN DATEDIFF(DAY, GETDATE(), T1.EXPDATE) > 0 THEN 'Lotes No Vencidos'
	END STATUSBATCHID
FROM DAXINVENTONHANDCONTAINER T1
INNER JOIN DAXPARKINGPOSITIONTABLE TBL2 ON T1.PARKINGPOSITIONID = TBL2.PARKINGPOSITIONID
WHERE T1.PARKINGSPACEID IS NOT NULL
AND T1.EXPDATE IS NOT NULL
AND TBL2.PARKINGSPACETRANSTYPE IN (3,4,7,9,10)) AS T2
GROUP BY T2.PARKINGSPACEID, T2.STATUSBATCHID
) TMP2 ON TMP1.PARKINGSPACEID = TMP2.PARKINGSPACEID AND TMP1.STATUSBATCHID = TMP2.STATUSBATCHID
GO