IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS  WHERE TABLE_NAME = 'DAXWMSLOCATIONAVAILPHYSICAL') DROP VIEW DAXWMSLOCATIONAVAILPHYSICAL
GO
CREATE VIEW [dbo].[DAXWMSLOCATIONAVAILPHYSICAL] AS
SELECT t1.INVENTLOCATIONID,
       t1.WMSLOCATIONID,
       ISNULL(SUM(t2.INVENTQTYAVAILPHYSICAL), 0) INVENTQTYAVAILPHYSICAL,
       ISNULL(SUM(t2.PdsCWAvailPhysical), 0) PDSCWAVAILPHYSICAL
FROM WMSLOCATION t1
LEFT JOIN DAXINVENTONHANDITEM t2 ON t1.INVENTLOCATIONID = t2.INVENTLOCATIONID
AND t1.WMSLOCATIONID = t2.WMSLOCATIONID
GROUP BY t1.INVENTLOCATIONID, t1.WMSLOCATIONID
GO